platform :ios, '7.0'
pod 'MKNetworkKit', '~>0.87'
pod 'AFNetworking', '~> 2.1.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'SDWebImage'
pod 'UIAlertView+Blocks', '~> 0.8.1'
pod 'FMDB', '~> 2.3'
pod 'FMDBHelpers', '~> 0.0.5'
pod 'MMMarkdown', '~> 0.3'
pod 'TNRadioButtonGroup', '~> 0.2'
pod 'TNCheckBoxGroup', '~> 0.1'
pod 'TTTAttributedLabel', '~> 1.10.1'
pod 'BorderButton', '~> 0.1.1'
pod 'MRoundedButton', '~> 1.0'