platform :ios, '7.0'
pod 'MKNetworkKit', '~>0.87'
pod 'AFNetworking', '~> 2.1.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'SDWebImage'
pod 'UIAlertView+Blocks', '~> 0.8.1'
pod 'FMDB', '~> 2.3'
pod 'FMDBHelpers', '~> 0.0.5'